version: "3"

services:
  db:
    image: mariadb:10.3
    restart: always
    env_file:
      - dbconfig.env
    ports:
      - "3306:3306"
    volumes:
        - mysql:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile 
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    tty: true

volumes:
  mysql:
